name: Update lambda

on:
  release:
    types: ["published"]

jobs:
  update_lambda:
    name: 'Pull code & update lambda'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: diasRibeirao/devops-atividade-4@master
        name: Update lambda code
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          function_name: lambda_devops
          region: us-east-1
        
